### ISSUE TITLE
Automate deployment of apps

### ISSUE THREAD

**Issue by chalenge** [faros-ai/faros-apps#37]
**Problem**
Currently the process to deploy apps is manual. This introduces possible gaps between the code status and the deployed apps and will make debugging issues harder.

**Solution**
Complete CD of apps. We should automate the process so that the code status reflects the exact apps that are currently deployed in the system.

**Alternatives**
Describe the alternatives you've considered. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context about the feature request here.

**Comment by tovbinm** [comment]
Let's move the deployment workflow to our internal repo.
